zombies_app/config/routes.rb
ZombiesApp::Application.routes.draw do
  resources :tweets

  resources :zombies

  root :to => 'Home#index'

end

zombies_app/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
end

zombies_app/app/models/zombie.rb
class Zombie < ActiveRecord::Base
  has_many :tweets
end

zombies_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

zombies_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = "Welcome to the Rails for Zombies Application"
  end

end

zombies_app/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

zombies_app/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
    end
  end
end

zombies_app/app/helpers/application_helper.rb
module ApplicationHelper
end

zombies_app/app/helpers/home_helper.rb
module HomeHelper
end

zombies_app/app/helpers/tweets_helper.rb
module TweetsHelper
end

zombies_app/app/helpers/zombies_helper.rb
module ZombiesHelper
end

zombies_app/app/views/home/index.html.erb
<h1>Home#index</h1>
	<p>Find me in app/views/home/index.html.erb</p>
<%=@home%>

zombies_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombiesApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

zombies_app/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

zombies_app/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

zombies_app/app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.status %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

zombies_app/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

zombies_app/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @tweet.status %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

zombies_app/app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :graveyard %><br />
    <%= f.text_field :graveyard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

zombies_app/app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

zombies_app/app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Graveyard</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.name %></td>
    <td><%= zombie.graveyard %></td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

zombies_app/app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

zombies_app/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>

<p>
  <b>Graveyard:</b>
  <%= @zombie.graveyard %>
</p>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>